version: '3.1'

networks:
  gradle_docker_net:

services:
  springboot:
    image: springio/gs-rest-service-patient
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    container_name: patient
    ports:
      - 7005:7005
      - 7006:7005
    networks:
      - gradle_docker_net
    depends_on:
      - consul
      - volunteer
      
  springboot:
    image: springio/gs-rest-service
    build:
     context: .
     dockerfile: ..\VolunteerApplication\Dockerfile
    restart: always
    container_name: volunteer
    ports:
      - 7002:7002
      - 7003:7002
    networks:
      - gradle_docker_net
  
  consul:
    image: bitnami/consul:latest
    container_name: consul
    ports:
      - 8500:8500
    volumes:
      - consul:/bitnami
    networks:
      - gradle_docker_net 

volumes:
  consul: